import type { CurrencyCode, Frequency } from '@/types';

export const DUMMY_USER_ID = '00000000-0000-0000-0000-000000000001';

export const CURRENCIES: Record<CurrencyCode, { symbol: string; name: string; locale: string }> = {
  GBP: { symbol: '£', name: 'British Pound', locale: 'en-GB' },
  USD: { symbol: '$', name: 'US Dollar', locale: 'en-US' },
  EUR: { symbol: '€', name: 'Euro', locale: 'de-DE' },
  CHF: { symbol: 'Fr', name: 'Swiss Franc', locale: 'de-CH' },
  SEK: { symbol: 'kr', name: 'Swedish Krona', locale: 'sv-SE' },
  NOK: { symbol: 'kr', name: 'Norwegian Krone', locale: 'nb-NO' },
  DKK: { symbol: 'kr', name: 'Danish Krone', locale: 'da-DK' },
  PLN: { symbol: 'zł', name: 'Polish Złoty', locale: 'pl-PL' },
  CZK: { symbol: 'Kč', name: 'Czech Koruna', locale: 'cs-CZ' },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint', locale: 'hu-HU' },
  RON: { symbol: 'lei', name: 'Romanian Leu', locale: 'ro-RO' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev', locale: 'bg-BG' },
  HRK: { symbol: 'kn', name: 'Croatian Kuna', locale: 'hr-HR' },
};

export const FREQUENCIES: Record<Frequency, string> = {
  daily: 'Daily',
  weekly: 'Weekly',
  biweekly: 'Every 2 weeks',
  monthly: 'Monthly',
  quarterly: 'Every 3 months',
  semiannual: 'Every 6 months',
  annual: 'Yearly',
};

export const SEVEN_YEARS_DAYS = 365 * 7 + 2; // +2 for leap years

export const TAGS: Record<string, { label: string; color: string; category: 'income' | 'expense' | 'both' }> = {
  // ── Expense ──────────────────────────────────────────────────────────────────
  food:          { label: 'Food & Drink',   color: '#f97316', category: 'expense' },
  transport:     { label: 'Transport',       color: '#3b82f6', category: 'expense' },
  housing:       { label: 'Housing',         color: '#8b5cf6', category: 'expense' },
  utilities:     { label: 'Utilities',       color: '#eab308', category: 'expense' },
  entertainment: { label: 'Entertainment',   color: '#ec4899', category: 'expense' },
  health:        { label: 'Health',          color: '#ef4444', category: 'expense' },
  shopping:      { label: 'Shopping',        color: '#14b8a6', category: 'expense' },
  dining:        { label: 'Dining Out',      color: '#fb923c', category: 'expense' },
  insurance:     { label: 'Insurance',       color: '#64748b', category: 'expense' },
  clothing:      { label: 'Clothing',        color: '#a855f7', category: 'expense' },
  personal_care: { label: 'Personal Care',   color: '#f43f5e', category: 'expense' },
  travel:        { label: 'Travel',          color: '#0ea5e9', category: 'expense' },
  education:     { label: 'Education',       color: '#2563eb', category: 'expense' },
  gifts:         { label: 'Gifts',           color: '#e879f9', category: 'expense' },
  tech:          { label: 'Tech & Gadgets',  color: '#06b6d4', category: 'expense' },
  childcare:     { label: 'Childcare',           color: '#f59e0b', category: 'expense' },
  pets:          { label: 'Pets',                color: '#84cc16', category: 'expense' },
  subscriptions: { label: 'Subscriptions',       color: '#7c3aed', category: 'expense' },
  groceries:     { label: 'Groceries',           color: '#65a30d', category: 'expense' },
  gym_fitness:   { label: 'Gym & Fitness',       color: '#dc2626', category: 'expense' },
  loan_repayment:{ label: 'Loan Repayment',      color: '#b45309', category: 'expense' },
  credit_card:   { label: 'Credit Card',         color: '#1d4ed8', category: 'expense' },
  mortgage:      { label: 'Mortgage',            color: '#0f766e', category: 'expense' },
  bank_fees:     { label: 'Bank Fees',           color: '#374151', category: 'expense' },
  charity:       { label: 'Charity & Donations', color: '#db2777', category: 'expense' },
  taxes:         { label: 'Taxes',               color: '#4b5563', category: 'expense' },
  home_maintenance:{ label: 'Home Maintenance',  color: '#92400e', category: 'expense' },
  beauty:        { label: 'Beauty & Hair',       color: '#be185d', category: 'expense' },
  parking:       { label: 'Parking & Tolls',     color: '#0369a1', category: 'expense' },
  hobbies:       { label: 'Hobbies',             color: '#7c2d12', category: 'expense' },
  // ── Income ───────────────────────────────────────────────────────────────────
  salary:        { label: 'Salary',              color: '#22c55e', category: 'income'  },
  freelance:     { label: 'Freelance',       color: '#10b981', category: 'income'  },
  investment:    { label: 'Investment',      color: '#6366f1', category: 'income'  },
  bonus:         { label: 'Bonus',           color: '#4ade80', category: 'income'  },
  rental:        { label: 'Rental Income',   color: '#34d399', category: 'income'  },
  pension:       { label: 'Pension',         color: '#2dd4bf', category: 'income'  },
  benefits:      { label: 'Benefits',        color: '#38bdf8', category: 'income'  },
  cashback:      { label: 'Cashback',        color: '#a3e635', category: 'income'  },
  dividends:     { label: 'Dividends',       color: '#818cf8', category: 'income'  },
  side_hustle:   { label: 'Side Hustle',     color: '#fb7185', category: 'income'  },
  gift_received: { label: 'Gift Received',   color: '#f472b6', category: 'income'  },
  tax_refund:    { label: 'Tax Refund',      color: '#60a5fa', category: 'income'  },
  business:        { label: 'Business',           color: '#c084fc', category: 'income'  },
  overtime:        { label: 'Overtime Pay',        color: '#16a34a', category: 'income'  },
  commission:      { label: 'Commission',          color: '#059669', category: 'income'  },
  interest:        { label: 'Interest',            color: '#0891b2', category: 'income'  },
  crypto:          { label: 'Crypto Gains',        color: '#7c3aed', category: 'income'  },
  stock_options:   { label: 'Stock Options',       color: '#4f46e5', category: 'income'  },
  royalties:       { label: 'Royalties',           color: '#9333ea', category: 'income'  },
  loan_received:   { label: 'Loan Received',       color: '#b45309', category: 'income'  },
  insurance_payout:{ label: 'Insurance Payout',    color: '#0f766e', category: 'income'  },
  redundancy:      { label: 'Redundancy Pay',      color: '#64748b', category: 'income'  },
  child_benefit:   { label: 'Child Benefit',       color: '#f59e0b', category: 'income'  },
  selling:         { label: 'Selling Items',       color: '#10b981', category: 'income'  },
  tips:            { label: 'Tips & Gratuities',   color: '#34d399', category: 'income'  },
  reimbursement:   { label: 'Reimbursement',       color: '#6ee7b7', category: 'income'  },
  scholarship:     { label: 'Scholarship',         color: '#60a5fa', category: 'income'  },
  government_grant:{ label: 'Government Grant',    color: '#38bdf8', category: 'income'  },
  inheritance:     { label: 'Inheritance',         color: '#a78bfa', category: 'income'  },
  maternity_pay:   { label: 'Maternity/Paternity Pay', color: '#f472b6', category: 'income'  },
  // ── Both ─────────────────────────────────────────────────────────────────────
  savings:       { label: 'Savings',         color: '#8b5cf6', category: 'both'    },
  other:         { label: 'Other',           color: '#6b7280', category: 'both'    },
};
